# Generated by Django 4.2.8 on 2024-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_worker_user_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employer_rating',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='worker_rating',
        ),
    ]
